jaffle_shop:

  target: prod
  outputs:
    prod:
      type: duckdb
      path: 'md:flight_jaffle_shop'
      threads: 4
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      threads: 24
